### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by ltsaprounis** [FedericoGarza/tsfeatures#10]
I've started working on an adapter for tsfeatures in sktime alan-turing-institute/sktime#968 but I'm running in some dependencies issues. 

The main problem is the strict requirements 
e.g. `scikit-learn==0.23.1` instead `of scikit-learn>=0.23.1` or just `scikit-learn`. 

Also entropy is now deprecated and replaced by https://github.com/raphaelvallat/antropy

**Comment by AzulGarza** [comment]
Hi! I've released the [0.3.0 version](https://pypi.org/project/tsfeatures/) addressing these issues.

Thanks!

**Comment by ltsaprounis** [comment]
Legend! thanks
