### ISSUE TITLE
Question about frequency

### ISSUE THREAD

**Issue by iLampard** [FedericoGarza/tsfeatures#12]
Hi, I have a question about the frequency setting in utils.py.

What does the frequency map mean here?  The code says, an hourly data has frequency  24, a daily data has frequency 1, but
why  weekly and yearly data all have 1 as frequency?

```
FREQS = {'H': 24, 'D': 1,
         'M': 12, 'Q': 4,
         'W':1, 'Y': 1}
```

Thanks in advance.

**Comment by AzulGarza** [comment]
Hi! `frequency` here is the number of observations per `cycle`. For instance, each hourly cycle has 24 hours. A great reference by Hyndman can be found [here](https://robjhyndman.com/hyndsight/seasonal-periods/). The dict `FREQS` considers the frequencies used by the [M4 Competition](https://www.sciencedirect.com/science/article/pii/S0169207019301128):

> i.e., 12 for monthly, four for quarterly, 24 for hourly and one for yearly, weekly and daily data. The reasoning behind this choice is that there is no obvious seasonality for the case of the weekly, daily and hourly data.
