### ISSUE TITLE
infered frequency

### ISSUE THREAD

**Issue by Saina199** [FedericoGarza/tsfeatures#15]
my signal is resampled to every 4H.  Although I have made sure to fill all nan values and have ds to include all time indices, tsfeatures cannot infer it properly.  If I need to set freq, should I put freq=4 or freq=6?  thanks

**Comment by AzulGarza** [comment]
Hi @Saina199,

The library uses the function `pd.infer_freq` to infer the frequency, so you can try the function over your dataset before using `tsfeatures`.

Since the signal is resampled every 4H, I think `freq=6` should work well (every 6 observations, a cycle of 24 hours is completed).

:)
