### ISSUE TITLE
Structure of df

### ISSUE THREAD

**Issue by fgvenegas** [FedericoGarza/tsfeatures#6]
Hi!

Please, could you add an example of how the input df should look? I don't understand columns ds and y.

Thanks :)

**Comment by AzulGarza** [comment]
Hi! 

I've added an [example](https://github.com/FedericoGarza/tsfeatures#use) of the structure; `ds` is the date column of the time series and `y` the value at that date. 

Please let me know if you have any problem. :)

**Comment by fgvenegas** [comment]
Thanks a lot!
