### ISSUE TITLE
hw_parameters, Param smoothing_slope

### ISSUE THREAD

**Issue by ronkremser** [FedericoGarza/tsfeatures#9]
Hi Federico,

thank you for this great work. I've got a question about the function _hw_parameters_, more precisely the parameter 'smoothing_slope':

Since _hw_parameters_ always returns 'nan' for any time series I use, is it possible, that 'smoothing_slope' should be renamed to 'smoothing_trend' ? Because if I do this, _hw_parameters_ returns valid values.

For the parameter names I had a look here:
https://www.statsmodels.org/dev/generated/statsmodels.tsa.holtwinters.ExponentialSmoothing.fit.html#statsmodels.tsa.holtwinters.ExponentialSmoothing.fit

Thank you very much

**Comment by AzulGarza** [comment]
Hi! I've released the [0.3.0 version](https://pypi.org/project/tsfeatures/) addressing these issues.

Thanks!
